# Generated by Django 4.2.16 on 2024-09-08 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('parent_menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='menu_manager.menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('parent_menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='menu_manager.menu')),
            ],
        ),
    ]
